### ISSUE TITLE
newsfeed.get id группы

### ISSUE THREAD

**Issue by Nikaladze** [AndrewShmig/Vkontakte-iOS-SDK-LV#108]
Я делаю запрос на получение новостей и если новость от группы, то ВК присылает "-ID", а если от человека - просто "ID". Также в этом ответе отдельно приходят данные о пользователях и группах, только там ID групп приходят без минуса. Проблема в том, что при переходе к десятичной системе отрицательные значения переводятся, как положительные. Соответственно в owner_id от групп приходят 720575... Как выйти с этой ситуации?
![- -2014-09-01- -13 59 47](https://cloud.githubusercontent.com/assets/6143281/4107620/5f72faec-31ca-11e4-93e4-5467163c1012.png)

**Comment by AndrewShmig** [comment]
> Проблема в том, что при переходе к десятичной системе отрицательные значения переводятся

О каком переводе идет речь? Где этот перевод осуществляется?
Проблема однозначно на вашей стороне и скорее всего в том, какой тип данных вы используете. NSUInteger? 

---

С уважением,
Шмиг Андрей Андреевич

Skype: sky-dos
Email: andrewshmig@yandex.ru

**Comment by Nikaladze** [comment]
Это скриншот того, что приходит. Т.е. в делегате: 

``` javascript
-(void) request:(VKRequest *)request response:(id)response
```

я вытягиваю ответ:

``` javascript
NSDictionary *responseDict = [response objectForKey:@"response"];
```

и результат на картинке выше. Я никуда ничего дополнительно не перевожу, просто если то, что приходит (720575...) перевести в 16-ую систему, то получим 0xbfffffffffff8ca3, я плохо помню, но минус как-то так и кодируется

**Comment by AndrewShmig** [comment]
А если пробовать осуществить такой же запрос на самом dev.vk.com со страницы документации? Всё верно выдаёт?
У меня просто пока только два варианта: 1) ВК что-то не то выдаёт 2) при преобразовании ответа сервера в JSON (NSJSONSerialization) происходит некорректное преобразование типов, что странно

---

С уважением,
Шмиг Андрей Андреевич

Skype: sky-dos
Email: andrewshmig@yandex.ru

**Comment by Nikaladze** [comment]
Здесь (http://vk.com/dev/newsfeed.get) поля source_id (если это группы) возвращаются минусовыми, потому похоже на второй вариант

**Comment by AndrewShmig** [comment]
Тогда даже не знаю, чем могу помочь. Попробуйте еще каким-то образом проверить, что же возвращает контакт… есть ли проблемы с отрицательными айдишниками при попытке получить информацию по другим запросам?

---

С уважением,
Шмиг Андрей Андреевич

Skype: sky-dos
Email: andrewshmig@yandex.ru

**Comment by Nikaladze** [comment]
Конечно, жесткий баян, но может кому-то поможет, кто столкнется с подобной ситуацией. Перевожу ID группы с минусом в HEX:

``` javascript
NSString *keyValue = [NSString stringWithFormat:@"%02lx",-[groupItem.gId longValue]];
```

Забиваю в Словарь нормальные данные по этому ключу

``` javascript
[groups setObject:groupItem forKey:keyValue];
```

Когда по ключу не нахожу инфу в пользователях, значит это скорее всего группы - начинаю искать в словаре по такому ключу:

``` javascript
NSString *hexValue = [NSString stringWithFormat:@"%02lx",[sourceId longValue]];
```

И восcтанавливаю нормальный ID

**Comment by Nikaladze** [comment]
Еще такой вопрос: есть возможность быстрого переключения на последнюю версию АПИ?

**Comment by AndrewShmig** [comment]
Быстрого? А в чем конкретно проблема? Давно уже не работал с ВК.

---

С уважением,
Шмиг Андрей Андреевич

Skype: sky-dos
Email: andrewshmig@yandex.ru

**Comment by Nikaladze** [comment]
В этих самых новостях приходит поле next_from, это что-то типа offset только более продвинутое,  а оно доступно в версии начиная с 5.13

**Comment by AndrewShmig** [comment]
Так какие трудности? СДК не может работать последней версией или что?

---

С уважением,
Шмиг Андрей Андреевич

Skype: sky-dos
Email: andrewshmig@yandex.ru

**Comment by Nikaladze** [comment]
Бывает, тупанул.
