### ISSUE TITLE
Access Token creation time

### ISSUE THREAD

**Issue by kirillivonin** [AndrewShmig/Vkontakte-iOS-SDK-LV#17]
При обращении к VKStorageItem.accessToken.creationTime всегда возвращается [[NSDate date] timeIntervalSince1970], таким образом, нельзя проверить, истек ли срок действия токена

**Comment by AndrewShmig** [comment]
Воспользуйтесь этим свойством класса VKAccessToken:

``` objective-c
/**
 Истекло ли время действия текущего токена доступа или нет.
 NO - если токен всё еще действует, иначе - YES.

 NO в следующих случаях:

 - Время истечения токена больше нуля и больше текущего времени.
 - Время истечения токена равно нулю и в списке доступов присутствует "offline" доступ

 */
@property (nonatomic, readonly) BOOL isExpired;
```

Кстати в документации есть информация об этом. Советую использовать.
Документация: https://github.com/AndrewShmig/Vkontakte-iOS-SDK-v2.0/tree/master/Project/Vkontakte-iOS-SDK-v2.0/docs

**Comment by kirillivonin** [comment]
я использую это свойство. как раз из-за описанной выше проблемы оно не действует:

NSTimeInterval currentTimestamp = [[NSDate date] timeIntervalSince1970];

```
if (self.expirationTime == 0 && [self hasPermission:@"offline"])
    return NO;
else
    return ((self.expirationTime + self.creationTime) < currentTimestamp);
```

сутки действия токена + текущее время, естественно, меньше текущего времени :)

**Comment by AndrewShmig** [comment]
@kirillivonin странно. 
self.liveTime = время жизни токена доступа, пусть будут сутки
self.creationTime = время _создания_ токена

Покажите пожалуйста description токена доступа.

**Comment by AndrewShmig** [comment]
@kirillivonin так, кажется я понимаю _почему_ у вас могут возникнуть проблемы такие.
Единственное место, где происходит инициализация времени создания токена доступа в этом методе:

``` objective-c
- (instancetype)initWithUserID:(NSUInteger)userID
                   accessToken:(NSString *)token
                      liveTime:(NSTimeInterval)liveTime
                   permissions:(NSArray *)permissions
{
    INFO_LOG();

    if (self = [super init]) {
        _userID = userID;
        _token = [token copy];
        _liveTime = liveTime;
        _permissions = [permissions copy];
        _creationTime = [[NSDate date] timeIntervalSince1970];
    }

    return self;
}
```

После чего этот метод больше не вызывается, а значит и время создания не меняется.
У вас же судя по всему этот методы вызывается не раз.

Было бы неплохо получить чуточку больше информации, чтобы понять _где_ ошибка и при каких действиях.

**Comment by kirillivonin** [comment]
Судя по логам, метод вызывается каждый раз, когда я пытаюсь залогиниться. Программа у меня рассчитана на одного пользователя. Вызывается почему-то после этого:

[[VKStorage sharedStorage] count] && [[[VKStorage sharedStorage].storageItems objectAtIndex:0] accessToken].isValid

**Comment by AndrewShmig** [comment]
@kirillivonin ох ты ёмаё)) ну вы много лишнего делаете.
После авторизации вызывайте сразу [VKUser currentUser] и будет вам счастье. Для одного пользователя вам не надо заморачиваться с индексами в хранилище и тд.
Да и вообще - не используйте хранилище как таковое. Есть класс VKUser, там все необходимые методы есть.
Я настоятельно советую вам прочитать сперва документацию или хабр: http://habrahabr.ru/post/185766/

**Comment by kirillivonin** [comment]
даже если так:

```
VKUser* me = [VKUser currentUser];
me.delegate = self;
if (me.accessToken.isValid){
    _loginCompletion(nil);
}
```

то в логах все равно:

+[VKStorage sharedStorage]
 -[VKStorage init]
-[VKStorage loadStorage]
 -[VKAccessToken initWithCoder:]
 -[VKStorage fullCacheStoragePath]
-[VKStorageItem initWithAccessToken:mainCacheStoragePath:]
 -[VKAccessToken copyWithZone:]

> > > -[VKAccessToken initWithUserID:accessToken:expirationTime:permissions:]
> > > -[VKCachedData initWithCacheDirectory:]
> > >  -[VKCachedData createDirectoryIfNotExists:]
> > > -[VKStorage fullCacheStoragePath]
> > > -[VKStorage isEmpty]
> > > -[VKStorage sharedStorage]

**Comment by AndrewShmig** [comment]
Тогда мне хочется взглянуть на проект в целом: где вызываете окно авторизации, какие методы делегатов реализовали, как вызываете методы пользовательского класса.

И прошу уточнить вопрос, который у вас: не получается настроить и запустить приложение? не получается осуществить запрос от лица пользователя?

Сейчас со всем разберемся и всё настроим.

**Comment by kirillivonin** [comment]
проблемы только в этом конкретном месте. то есть, если облигатно запускать 

[[VKConnector sharedInstance] startWithAppID:kVKAppID
                                      permissons:[kVKPermissionsArray componentsSeparatedByString:@","]];

все ок. заметил. честно говоря, только сегодня после истечения срока действия токена :)

перед кодом, написанным выше, ставлю только [[VKConnector sharedInstance] setDelegate:self];

**Comment by AndrewShmig** [comment]
@kirillivonin посмотри в делегате VKConnectorDelegate метод:

``` objective-c
/** Метод, вызов которого сигнализирует о том, что токен стал недействительным,
 срок его действия истёк.

 @param connector объект класса VKConnector отправляющий сообщение.
 @param accessToken токен доступа, срок действия которого истёк.
 */
- (void)   VKConnector:(VKConnector *)connector
accessTokenInvalidated:(VKAccessToken *)accessToken;
```

и реализуй его у себя в делегате. Если вызывается этот метод, то в нем должен быть вызов окна авторизации для обновления токена доступа и его срока действия.

**Comment by kirillivonin** [comment]
хотелось бы, чтобы в вызове, подобном моему, creationTime не обновлялся, все-таки :)

**Comment by AndrewShmig** [comment]
@kirillivonin пока не увижу весь код ничего не могу сказать, ибо тот пример вызовов, что вы показали ничего не дает.

**Comment by AndrewShmig** [comment]
@kirillivonin однако понял в чем могла быть проблема. исправил.
проверьте теперь пожалуйста.
