### ISSUE TITLE
[2.7.1] Не отрабатывает событие  VKConnection:willHideModalView при закрытии модального окна

### ISSUE THREAD

**Issue by AlexKru** [AndrewShmig/Vkontakte-iOS-SDK-LV#23]
Если пользователь просто закрывает окно, не вводя никаких данных ( модальное окно открылось - и нажали на крестик ), то указанное событие не срабатывает. 
Для примера, мне нужно выключить UISwitch если пользователь не авторизовался

-(void)VKConnector:(VKConnector *)connector willHideModalView:(KGModal *)view
{
    NSLog(@"vk user: %@", [VKUser currentUser]);
    if( [VKUser currentUser] == nil ){
        [self.vkConnectSwitcher setOn:NO];
    }
}

**Comment by AndrewShmig** [comment]
Проверил, действительно есть такой косяк в KGModal.
В ближайшее время посмотрю что и как там.
