### ISSUE TITLE
friendsGet w/ token

### ISSUE THREAD

**Issue by masterrr** [AndrewShmig/Vkontakte-iOS-SDK-LV#25]
Hello guys, it would be awesome if you made friendsGet method is also available to call w/ token = YES in next milestone; 

For instance, contacts fields are not going to be returned because of always “show only to friends” privacy option enabled.

**Comment by AndrewShmig** [comment]
Hm... interesting remark. 
Thanks, I'll check what can be done there.

**Comment by AndrewShmig** [comment]
You can do this way:

``` objective-c
[[VKUser currentUser] friendsGet:@{
   @"access_token": [VKUser currentUser].accessToken.token,
   @"uids": @"1,2,3,4",
   @"fields": @"nick,online,photo_100"
}];
```

And its better not to add another method friendsGet _with_ accessToken.
Do you have better suggestions?
