### ISSUE TITLE
Create cocoa pods

### ISSUE THREAD

**Issue by Samback** [AndrewShmig/Vkontakte-iOS-SDK-LV#26]

**Comment by AndrewShmig** [comment]
На днях подключимс, но вот потом не факт, что не забуду обновлять там версии.

**Comment by Samback** [comment]
Я вам буду напоминать)))))

**Comment by Samback** [comment]
И первую версию обновите. Я вам там писал.

**Comment by AndrewShmig** [comment]
@Samback идёт, тогда сразу пишите туда на что менять и на что обновлять))

**Comment by AndrewShmig** [comment]
Done.

**Comment by AndrewShmig** [comment]
@Samback https://github.com/CocoaPods/Specs/blob/master/Vkontakte-iOS-SDK-v2/2.7.0/Vkontakte-iOS-SDK-v2.podspec

**Comment by Samback** [comment]
Unable to read the license file 
/Pods/Vkontakte-iOS-SDK-v2/Project/Vkontakte-iOS-SDK-v2.0/LICENSE.txt`for the spec`Vkontakte-iOS-SDK-v2 (2.7.0)`

**Comment by AndrewShmig** [comment]
@Samback странно, всё прошло успешно.

**Comment by Samback** [comment]
И еще, это больше всего что не ваша проблема, но возможно вы знаете почему 
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_VKConnector", referenced from:

**Comment by AndrewShmig** [comment]
@Samback, может фрэймворк какой забыли подключить? Перепроверьте. 
+сделайте Clean проекта

**Comment by Samback** [comment]
Я создал новый проект, но там та же беда

**Comment by Samback** [comment]
- если просто перетянуть файлы либы в проект, всё работает.

**Comment by AndrewShmig** [comment]
@Samback , только сейчас обратил внимание на то, что путь-то с ошибкой:
/Pods/Vkontakte-iOS-SDK-v2/<b>Project/</b>Vkontakte-iOS-SDK-v2.0/LICENSE.txt
Выделенного жирным там не должно быть

**Comment by Samback** [comment]
Я так понимаю здесь тоже не должно быть Project
![2013-08-22 09 10 10](https://f.cloud.github.com/assets/768673/1006768/993f69e6-0af1-11e3-8886-43b0a595be55.png)

**Comment by AndrewShmig** [comment]
@Samback правильно понимаете.

**Comment by Samback** [comment]
А как это можно пофиксить ?

**Comment by AndrewShmig** [comment]
@Samback безпонятия, поды не юзаю. спросите в офф репе.

**Comment by Samback** [comment]
Спасибо, спрошу.

**Comment by lonkly** [comment]
Под то как не работал, так и не работает. В самом поде нету .m файлов

**Comment by AndrewShmig** [comment]
@lonkly где мой косяк? Что поправить?

**Comment by lonkly** [comment]
а хз, как-то не так podspec создан :( Все ли там депенденси прописаны, и пути правильно?

**Comment by AndrewShmig** [comment]
@lonkly проверил пути и зависимости - всё нормально. Всё в самой SDK есть, ничего, кроме дополнительного подключения кварца не надо делать.

**Comment by AndrewShmig** [comment]
Разбираюсь сам. Как только решу проблему - сообщу.

**Comment by AndrewShmig** [comment]
@lonkly @Samback исправил ошибки, которые были и запросил их на merge в репе со спеками. ждемс. должно работать правильно.

@lonkly таки да, из-за неверного указания регэкспа при выборе/фильтрации файлов там не было *.m файлов
 @Samback проверил пути (поставил поды, обновился), всё правильно в текущем варианте.
