### ISSUE TITLE
- (void)VKRequest:(VKRequest *)request response:(id)response; NSMutableArray?

### ISSUE THREAD

**Issue by Samback** [AndrewShmig/Vkontakte-iOS-SDK-LV#28]
Вопрос наверно более философский, чем технический :)
Почему было решено добавить прослойку массива вместо Dictionary?
Может я не глубоко копнул просто сейчас выходит надо сделать так 
    - (void)VKRequest:(VKRequest *)request response:(id)response
{
NSDictionary *userInfo = response[@"response"][0];
}
Почему нельзя было сделать просто 
NSDictionary *userInfo = response[@"response"]

**Comment by AndrewShmig** [comment]
Немного не понимаю о чем вы (укажите где этот участок в коде)
response - это Foundation объект, который может быть как словарём, так и массивом.

**Comment by Samback** [comment]
@protocol VKRequestDelegate <NSObject>

@required
/**
@name Обязательные
_/
/_\* Возвращает ответ сервера в виде Foundation объекта

@param request запрос к которому относится вызов метода делегата
@param response ответ сервера в виде Foundation объекта
*/
- (void)VKRequest:(VKRequest *)request
       response:(id)response;

Просто интересно почему он вот так возвращается:
  response =     (
                {
            "can_post" = 0;
            "can_see_all_posts" = 0;
            "can_see_audio" = 1;

Я имею ввиду что мы получаем response (как NSDictionary c единственным ключом  @"response" ) в котором сидит массив с единственным элементом (нулевым), в котором  сидит NSDictionary c необходимыми данными, вот мой вопрос был в том зачем массив в которм только один элемент если можно было бы сделать просто 
  response =     {
            "can_post" = 0;
            "can_see_all_posts" = 0;
            "can_see_audio" = 1;

**Comment by AndrewShmig** [comment]
@Samback зачем они так сделали не знаю, но смею предположить, что для удобства обработки ошибок, ответов после загрузки файлов и тд.
