### ISSUE TITLE
education, school, universities не отдает

### ISSUE THREAD

**Issue by Samback** [AndrewShmig/Vkontakte-iOS-SDK-LV#29]
Через либу перестало отдавать всё что связанное с образованием что бы проверить подставил все поля:
nickname, screen_name, sex, bdate, city, country, timezone, photo_50, photo_100, photo_200_orig, has_mobile, contacts, education, online, counters, relation, last_seen, status, can_write_private_message, can_see_all_posts, can_see_audio, can_post, universities, schools
Отдало все кроме 
universities, schools,education
хотя здесь все отдает:
https://vk.com/dev/users.get

**Comment by AndrewShmig** [comment]
Проверил, не выдаёт. Перекушу и разберусь.

**Comment by AndrewShmig** [comment]
``` objective-c
    [[VKUser currentUser] setDelegate:self];
    [[VKUser currentUser] info:@{
            @"user_id": @"205387401",
            @"fields": @"nickname,screen_name,sex,bdate,city,country,timezone,photo_50,photo_100,photo_200_orig,has_mobile,contacts,education,online,relation,last_seen,status,can_write_private_message,can_see_all_posts,can_post,universities,schools,education"
    }];
```

![screen shot 2013-08-26 at 4 07 29 pm](https://f.cloud.github.com/assets/2047836/1025569/3c1ee9d0-0e48-11e3-99de-1213b0322da4.png)

**Comment by Samback** [comment]
Странно недавно не отдавал, может глюк какой был... Доберусь домой еще раз посмотрю может что-то изменилось.... Education  я так понимаю тоже норм отдает...

**Comment by AndrewShmig** [comment]
Проверьте пользователя у которого вы запрашиваете данные. Может доступ к странице закрыт или еще что?
То, что я выше привел - это прямо из документации с учетной записью Тома Круза.
