### ISSUE TITLE
Таймаут у _innerWebView в VKConnector никак не обрабатывается

### ISSUE THREAD

**Issue by armed** [AndrewShmig/Vkontakte-iOS-SDK-LV#30]
Насколько я вижу, в VKConnectorDelegate объявлены методы:

``` objective-c
    - (void)   VKConnector:(VKConnector *)connector
    connectionErrorOccured:(NSError *)error;

    - (void)VKConnector:(VKConnector *)connector
    parsingErrorOccured:(NSError *)error;
```

Но они нигде не вызываются и в случае отсутствия интернета, окно авторизации подвисает.

PS. большое спасибо за статьи на хабре про Core Data.

**Comment by AndrewShmig** [comment]
@armed ну эти оба метода не о том, что называется.
Насчет таймаута - да, только потом заметил, что такая проблемка есть. Я немного иначе тестировал.

PS. Ух, даже здесь отписываются :) Пожалуйста, приятно знать, что народ читает.

**Comment by AndrewShmig** [comment]
@armed проверьте теперь.
Исправил косяк.

**Comment by armed** [comment]
@AndrewShmig, да все замечательно. Я вчера у себя чтобы пройти ваш урок, делал что-то подобное.

**Comment by AndrewShmig** [comment]
@armed , как практическая часть урока? Удалась? Получилось реализовать?

**Comment by armed** [comment]
@AndrewShmig, да все получилось. Я имею уже некоторый опыт с Core Data по одному проекту. Это для меня было, своего рода, закрепление материала. Ну и AppCode, как все остальные продукты от JetBrains на высоте. Жду когда они реализуют недостающий функционал, чтобы не прыгать в XCode и будет вообщ блеск.

Мне больше был интересен ваш туториал со стороны VK API.

**Comment by AndrewShmig** [comment]
@armed вторая версия мне самому нравится SDK, надеюсь так сказать спрос на неё будет. К тому же исправлять баги и добавлять что-то новое не проблема.

Но примеров-то вроде хватает и в РидМи на Гитхабе с Vkontakte iOS SDK v2. На Хабре простейший пример был.
