### ISSUE TITLE
В качестве Networking использовать AFNetworking.

### ISSUE THREAD

**Issue by KanybekMomukeyev** [AndrewShmig/Vkontakte-iOS-SDK-LV#31]
Почему бы не использовать уже готовую библиотеку ?
Вот например, Instagram IOS Client
https://github.com/stuartkhall/Instagram
Использовал AFNetworking, получилось отлично.

**Comment by AndrewShmig** [comment]
2 "потому что":
1) уже всё написано
2) не люблю блоки и не везде они вписываются "архитектурно" красиво

Искренне рад за инстаграм.

Что Вас конкретно в текущей реализации ВК СДК в2 не устраивает? Какие-то проблемы? Если есть, то сообщите и мы исправим. Если есть предложения - пишите, обдумаем и возможно реализуем.
Ну а если совсем не нравится, то форк и вперёд... )) Всё же открыто!

**Comment by AndrewShmig** [comment]
Если хотите блоки, то Вам сюда: https://github.com/AndrewShmig/ASASocialServices

**Comment by KanybekMomukeyev** [comment]
"Что конкретно ВК СДК в2 не устраивает?"
Хотелось бы видеть больше блоков, нежели делегатов.

Спасибо за https://github.com/AndrewShmig/ASASocialServices

**Comment by AndrewShmig** [comment]
@KanybekMomukeyev во второй версии мало вероятно, что будут блоки.
Они будут в том случае, если я прям очень часто буду слышать эту просьбу.
