### ISSUE TITLE
User authorization failed: invalid access_token.

### ISSUE THREAD

**Issue by tonyhex** [AndrewShmig/Vkontakte-iOS-SDK-LV#36]
Внедрил новую версию sdk в свое приложение. При попытке получить профиль пользователя выдает ошибку
"error_code" = 5;
"error_msg" = "User authorization failed: user revoke access for this token.";
Думал косяк в моих действиях. Долго мучался, потом загрузил Ваш тестовый проект.
Запускаю, логинюсь, даю доступ и вижу в консоли:
error: {
    "error_code" = 5;
    "error_msg" = "User authorization failed: invalid access_token.";
    "request_params" =     (
                {
            key = oauth;
            value = 1;
        },
                {
            key = method;
            value = "friends.get";
        },
                {
            key = "access_token";
            value = "{\n    \"Creation time\" = 1382305356;\n    \"Expiration time\" = 1382391756;\n    Permissions =     (\n        photos,\n        friends,\n        wall,\n        audio,\n        video,\n        docs,\n        notes,\n        pages,\n        status,\n        groups,\n        messages\n    );\n    Token = abc0a9a5027c52bbe77e6647b5fa033d4f36b02f5cc6789bdf880bfd94267bcb1e7c05174d407e255df06;\n    \"User ID\" = 18165897;\n}";
        },
                {
            key = fields;
            value = "nickname,screen_name,sex,bdate,city,country,timezone,photo_50,photo_100,photo_200_orig,has_mobile,contacts,education,online,relation,last_seen,status,can_write_private_message,can_see_all_posts,can_post,universities";
        },
                {
            key = "user_id";
            value = 58487857;
        }
    );
}

Так же пробовал подставлять id своего приложения - та же ошибка.

Пример со старой версией sdk работает нормально.

**Comment by AndrewShmig** [comment]
Ошибки уже не должно быть, была исправлена вот в этом коммите: https://github.com/AndrewShmig/Vkontakte-iOS-SDK-LV/commit/ca69ea1208ce29ccb1cf3d7b748441c4801774a4

Сделайте просто чекаут самой последней версии ( https://github.com/AndrewShmig/Vkontakte-iOS-SDK-LV.git ), в разделе Releases просто не зарелизил исправленную версию, ибо еще могу внести кое-какие изменения.
