### ISSUE TITLE
Неправильная ориентация при VKConnector - (void)startWithAppID:(NSString *)appID permissons:(NSArray *)permissions delegate:(id<VKConnectorDelegate>)delegate;

### ISSUE THREAD

**Issue by horovodovodo4ka** [AndrewShmig/Vkontakte-iOS-SDK-LV#37]
Если приложение запускалось в вертикальной ориентации, то при изменении на горизонтальную, окно авторизации (другие не видела) получает неверные размеры:

// настраиваем попап окно для отображения UIWebView
        CGRect frame = [[UIScreen mainScreen] bounds];

Пример такой проблемы: http://stackoverflow.com/questions/2664980/uiscreen-applicationframe-returning-incorrect-rectangle-on-landscape-application

**Comment by horovodovodo4ka** [comment]
Как вариант навскидку:
// настраиваем попап окно для отображения UIWebView
CGRect frame = ((UIView*)[[[[UIApplication sharedApplication] keyWindow] subviews] lastObject]).bounds;

**Comment by AndrewShmig** [comment]
@xbitstream , спасибо за репорт!
Сегодня постараюсь исправить!

**Comment by Samback** [comment]
а когда будет обновление cocoa pods ?

**Comment by AndrewShmig** [comment]
@Samback скорее всего завтра. Сейчас задачу создам.
