### ISSUE TITLE
Не могу понять, как воскресать, если сменил ip адрес?

### ISSUE THREAD

**Issue by ichina** [AndrewShmig/Vkontakte-iOS-SDK-LV#41]
при смене ip запросы ругаются что токен выдан на другой ip, а ссылки на аудио ваще не работают

**Comment by ichina** [comment]
перелогиниваться через вебформу?

**Comment by AndrewShmig** [comment]
Вотс: https://github.com/AndrewShmig/Vkontakte-iOS-SDK-LV/issues/33
Да, при смене айпишника надо перелогиневаться, тобишь обновлять аксес токен.

**Comment by AndrewShmig** [comment]
А что со ссылками на аудио?

**Comment by ichina** [comment]
эмм, ну если сменился ip адрес, то по ссылке на аудио уже ничего не скачать, в документации vk api, вообщем так и написано:
![2013-10-28 21 02 18](https://f.cloud.github.com/assets/1898138/1421840/c2f43a56-3ff2-11e3-8c6e-6e0f989489d1.png)

**Comment by ichina** [comment]
кароч, для всяких плееров наверн нужен доверенная авторизация

**Comment by AndrewShmig** [comment]
@ichina под доверенной подразумеваешь с offline правом?

**Comment by ichina** [comment]
ну я не знаю что такое offline право, c доверенной авторизацией можно авторизовываться через свои формы без всяких OAuth, токен не будет привязан к ip, и timestamp(или expiredDate) примерно на 3 месяца

**Comment by AndrewShmig** [comment]
@ichina интересно, что-то я пропустил. А можно ссылочку на инфу про свои формы?

**Comment by ichina** [comment]
![2013-10-28 21 25 17](https://f.cloud.github.com/assets/1898138/1422060/09066d36-3ff6-11e3-9678-bb5190fbecb9.png)

**Comment by ichina** [comment]
http://vk.com/dev/auth_direct здесь читай

**Comment by ichina** [comment]
просто нужно проходить аппрув у саппорта vk.com

**Comment by ichina** [comment]
когда проходил первый конкурс по vk.com для iOS, всем участникам раздавали прямую авторизацию, помню её потом тока через полгода отобрали у пролетевших

**Comment by AndrewShmig** [comment]
@ichina тьфу блин, понял о какой прямой авторизации идет речь. Да сталкивался с ней. + ко всему получить аппрув будет очень сложно.

**Comment by ichina** [comment]
@AndrewShmig слух, а можно какнить показывать webview только тогда, когда она уже загрузила форму OAuth,а то когда запрос с куками сразу возращает токен както не красиво выглядит, что появляеться и сразу исчезает(((

**Comment by AndrewShmig** [comment]
@ichina кстати раньше такой вариант обрабатывался. По-моему он сейчас есть, но в первой версии.
Если хочешь и очень надо - пиши отдельный issue и описывай что надо, я на днях сделаю.

**Comment by ichina** [comment]
я бы лучше б заралил бы request на то чтоб при смене токена, sdk само пыталось бы его перегенерить, пускай той же OAuth

**Comment by AndrewShmig** [comment]
@ichina имеешь ввиду перегенерировать автоматом без участия пользователя? а уж если требуется пользователю ввести что-то, то отображается окно?
В любом случае давай в виде отдельного фитч-реквеста и я на днях подумаю, каким образом лучше это внедрить.

**Comment by ichina** [comment]
oke
