### ISSUE TITLE
Неожиданное конструирование запросов VKUser

### ISSUE THREAD

**Issue by setoff** [AndrewShmig/Vkontakte-iOS-SDK-LV#42]
По-умолчанию accessToken в некоторых случаях к запросу не добавляется.
Например, запрос фото-альбомов.
Довольно странно запрашивать [[VKUser currentUser] photosGetAlbums];
и не получать альбомов для currentUser.
Как выход можно добавить метод photosGetAlbumsForUser:(NSString_)ownerId withOptions:(NSDictionary_)opt; который бы обеспечивал требуемую гибкость.

**Comment by AndrewShmig** [comment]
@setoff точно последнюю версию используете?)

**Comment by setoff** [comment]
Только что из CocoaPods залил. Видимо последняя релизная )

**Comment by AndrewShmig** [comment]
@setoff в кокоаподах еще не обновил

**Comment by AndrewShmig** [comment]
Смотрите самую последнюю релизнутую версию :)

**Comment by setoff** [comment]
Хорошо, спасибо.
