### ISSUE TITLE
Access token не добавляется, если словарь опций пустой

### ISSUE THREAD

**Issue by setoff** [AndrewShmig/Vkontakte-iOS-SDK-LV#43]
Не проверяется options на nil в
- (NSDictionary *)addAccessTokenKey:(NSDictionary *)options

Из-за этого не добавляется accessToken к запросу.

**Comment by AndrewShmig** [comment]
@setoff а можно пример вызовов? Хочу посмотреть на пример.

ПС
Я так понимаю передаете не пустой словарь, а nil. Не дело)

**Comment by setoff** [comment]
Почему я не могу передать пустой словарь?))
Если я не передаю никаких аргументов, то nil передавать — нормальная практика. 

К тому же исправляется минимальными усилиями ;)

**Comment by AndrewShmig** [comment]
@setoff done)
