### ISSUE TITLE
Should I remove VKModal class?

### ISSUE THREAD

**Issue by AndrewShmig** [AndrewShmig/Vkontakte-iOS-SDK-LV#44]
Subj. Will it be better to present a UIWebView as modal window?

**Comment by agitka** [comment]
Yes. Prefer this.
- [x] less code
- [x] less dependencies
- [x] easy to customize

**Comment by AndrewShmig** [comment]
@agitka
Maybe its better to allow developer to place UIWebView where he wants (without showing modal window)?

**Comment by agitka** [comment]
@AndrewShmig I don't analyze appstore apps which works with vk. Although, there's above option satisfies new design and that option is temporary, because serious app can request direct type of authorization from vk support. So the option is compromise.

PS Я понимать русский языка. Шучу, могу на русском писать.

**Comment by AndrewShmig** [comment]
@agitka кстати только сейчас вспомнил, что в приложении нет возможности авторизоваться с использованием логина и пароля пользователя.
Добавил бы опцию, но я проверить не смогу, ибо аппрув получить почти нереально, уже несколько раз сталкивался с администрацией/поддержкой.

Ну а насчет русского: подтягиваем английский) lingualeo в руки))

**Comment by agitka** [comment]
@AndrewShmig Ты имеешь в виду суппорт вк или аппле? Я полагаю вариант, что сначала делаем вышеуказанное, попадаем в аппстор, потом просим вк. По-моему такой вариант для обычный смертных.

**Comment by AndrewShmig** [comment]
@agitka я про суппорт ВК. Мне там вообще сказали, что не популярным приложениям такое не выдадут. То есть вариант опубликовать на аппсторе и попросить заапрувить в ВК имхо нереально.

**Comment by agitka** [comment]
@AndrewShmig Это прикольно. Ну получается делаем модальный вариант, становимся популярными. Здесь кастомизации впрочем очень мало можно сделать, они же как раз по юзер агенту и дают страницу входа, то есть как раз целый экран и нужен. Куда-то впихнуть или украсить  это окно, я сложно себе представляю.

**Comment by AndrewShmig** [comment]
@agitka тоже верно, особо не поиздеваешься, но вот само модальное окно (вплоть до верхнего хедера) программисту может понадобиться переделать, хотя единичный случай скорее всего будет.
Так что да, надо в модальный его закинуть.

**Comment by ichina** [comment]
кто нить кстати пробовал у этой OAuth формы удалить бекграунд? скока не пытался так и не разобрался с этими CSS. было б оч здорово если б кто помог

**Comment by AndrewShmig** [comment]
@ichina имеешь ввиду удаление белого фона со страницы авторизации ВК? А зачем?

**Comment by agitka** [comment]
@ichina Я думаю ВК может забанить за такие штучки.

**Comment by ichina** [comment]
@AndrewShmig ну ща с появлением ios7 все так сохнут по флэту и по блюру, чтоб круто б былоб свой очумечий заблюренный бэкграунд подставить))
@agitka  а за что собстна забанить то могут?

**Comment by AndrewShmig** [comment]
@ichina пригодиться: http://sree.cc/iphone/how-to-execute-javascript-in-uiwebview
Не знаю, можно ли там по ДУМу проходиться и убирать какие-то элементы, но... что есть, то есть - пробуй)

**Comment by agitka** [comment]
@ichina ты манипулируешь процессом регистрации. тонкая грань, лучше спросить у официальных лиц вк.

**Comment by ichina** [comment]
@AndrewShmig а как я могу удалить текущий access_token?

**Comment by AndrewShmig** [comment]
@ichina только путём удаления записи пользователя из хранилища.

**Comment by AndrewShmig** [comment]
@ichina думаю ознакомившись еще и с этим http://habrahabr.ru/post/185766/ станет понятней что и как в SDK сделано и зачем.
