### ISSUE TITLE
VKRequestManager::execute

### ISSUE THREAD

**Issue by agitka** [AndrewShmig/Vkontakte-iOS-SDK-LV#46]
wrapper for "execute" method

**Comment by AndrewShmig** [comment]
Link: https://vk.com/dev/execute
Глянем вечером, что здесь и как.

**Comment by agitka** [comment]
Да просто один nsstring в параметр и еще серверные методы есть с точкой, обрати внимание, надо обработать ситуацию(ниже инструкция).

**Comment by agitka** [comment]
Хранимые процедуры позволяют исполнять код на стороне сервера API аналогично методу execute, но без передачи кода процедуры по сети.

Использование хранимых процедур рекомендовано для мобильных приложений с целью экономии трафика.

Вы можете вызвать созданные в интерфейсе хранимые процедуры, используя следующую конструкцию:

https://api.vk.com/method/execute.ИМЯ_ПРОЦЕДУРЫ?СПИСОК_ПАРАМЕТРОВ

Переданные параметры будут доступны внутри кода процедуры в виде полей объекта Args, например, если Вы передали ?user=123, то значение этой переменной будет доступно в Args.user.

**Comment by AndrewShmig** [comment]
@agitka а где подробнее про хранимые процедуры можно глянуть? Полистал документацию, но найти не могу.

**Comment by agitka** [comment]
Thanks.

**Comment by AndrewShmig** [comment]
@agitka you are welcome) I have also added VK iOS SDK to CocoaPods.
