### ISSUE TITLE
Обработка ситуации, когда app ВКонтакте удален

### ISSUE THREAD

**Issue by mkll** [AndrewShmig/Vkontakte-iOS-SDK-LV#50]
Если удалить приложение из ВКонтакте, то при попытке залогиниться пользователь приложения iOS увидит кусочек JSON'а (см. скриншот). По-идее, это должен видеть разработчик, но никак не пользователь.
![ios simulator screen shot 03-11-2013 01 56 24](https://f.cloud.github.com/assets/1652009/1459818/58ec3cc0-43f9-11e3-9b6f-dc6663202ea3.png)

**Comment by AndrewShmig** [comment]
@mkll понял, завтра исправлю. спасибо за репорт.

**Comment by AndrewShmig** [comment]
В VKConnectorDelegate добавлен новый метод, который будет вызываться в том случае, если приложение к которому происходит запрос было удалено:

``` objective-c
/** Метод, вызов которого сигнализирует о том, что приложение в ВК, которое
используется для авторизации пользователя, было удалено.

@param connector объект класса VKConnector отправляющий сообщение
@param error объект ошибки содержащий описание причины возникшей ошибки
*/
- (void)  VKConnector:(VKConnector *)connector
applicationWasDeleted:(NSError *)error;
```

Далее программист сам решает, что делать. Окно авторизации не будет отображено. Смотреть новую [релизную](https://github.com/AndrewShmig/Vkontakte-iOS-SDK-LV/releases) версию СДК.

**Comment by KaaPex** [comment]
Метод applicationWasDeleted вызывается даже, если приложение не было удалено.

**Comment by AndrewShmig** [comment]
@KaaPex сейчас гляну, хотя странно.

**Comment by mkll** [comment]
Только что проверил - не вызывается.

**Comment by KaaPex** [comment]
Странно тогда:
![2013-11-04 13 12 20](https://f.cloud.github.com/assets/869685/1463550/405a4790-4531-11e3-97ed-e7914aa9ae68.png)

**Comment by AndrewShmig** [comment]
@KaaPex идентификатор приложения можно? Проверю у себя.

**Comment by KaaPex** [comment]
3974432

**Comment by AndrewShmig** [comment]
@KaaPex косяк есть, подтверждаю.
