### ISSUE TITLE
Whats the best way to show popup window?

### ISSUE THREAD

**Issue by AndrewShmig** [AndrewShmig/Vkontakte-iOS-SDK-LV#58]
Modal window or leave the same way we have now?

**Comment by agitka** [comment]
I've thought about premade uiwebview or uicontroller with uiwebview inside, that developer can embed how he wants.

**Comment by AndrewShmig** [comment]
@agitka just to give a programmer an uiwebview and let him choose the way he wants to display it?

**Comment by agitka** [comment]
@AndrewShmig  I mean "Necessity and sufficiency". I think sdk must do minimal maximum without further torment with rasp.

**Comment by AndrewShmig** [comment]
@agitka got it. I'll think about it and what should be done.
