### ISSUE TITLE
Document all undocumented methods

### ISSUE THREAD

**Issue by AndrewShmig** [AndrewShmig/Vkontakte-iOS-SDK-LV#59]
Including VKModal, NSString+Utilities, etc

**Comment by agitka** [comment]
It's unnecessary, because something is not important must be encapsulated if you belong OOP. I mean utilities and foreign libs. Of course IMHO.

**Comment by AndrewShmig** [comment]
@agitka maybe you are right... too much unneeded documentation on methods which no one will use (they are used only for internal purposes)
