### ISSUE TITLE
Асинхронные запросы с блоками

### ISSUE THREAD

**Issue by ealeksandrov** [AndrewShmig/Vkontakte-iOS-SDK-LV#6]

**Comment by notxcain** [comment]
Не забыть добавить возможность отмены запроса.

**Comment by AndrewShmig** [comment]
@denis-mikhaylov про это совсем забыл. Спасибо что напомнили.

**Comment by AndrewShmig** [comment]
@ealeksandrov блоки пока не планируются. Подумаю, каким образом их лучше всего вписать в общую картину. Пока работа происходит через делегатов.

@denis-mikhaylov отмену запроса добавил.
