### ISSUE TITLE
POST requests are not cached... all methods use POST and thats sad.

### ISSUE THREAD

**Issue by AndrewShmig** [AndrewShmig/Vkontakte-iOS-SDK-LV#62]
Something should be done with this: 
1) Change some methods to use GET if they really need it
2) Use POST only when new data are posted

Shit...

**Comment by agitka** [comment]
I think you might modificate method (configureRequestMethod) for support http method of request, but also we need to review that where "get" or "post" must be. Plain sailing is to find where be uses "post" in name.  

Now I've looked list of methods and plain sailing is cancel. It needs more work. You can keep "get" for all, except for methods that sending message or video or photo.

**Comment by agitka** [comment]
or audio or notes or docs) But it's easy to mistake.

**Comment by AndrewShmig** [comment]
@agitka I am working on this right now. 
If method changes something on any VK server - use POST
if method just gets information - use GET
