### ISSUE TITLE
UIWebView в новой сервии - маленького размера

### ISSUE THREAD

**Issue by mkll** [AndrewShmig/Vkontakte-iOS-SDK-LV#63]
В принципе, он и когда был на весь экран, тоже не помещался (но тут уж сорри, ничего не поделать), но сейчас это какое-то издевательство над пользователем. Я легко могу найти десяток людей, которые просто не сообразят, что надо этот экран проскроллить вниз, чтоб добраться до остальных полей и кнопок.
![ios simulator screen shot 10-11-2013 13 19 40](https://f.cloud.github.com/assets/1652009/1508138/6fe7f65e-49d9-11e3-9d34-8ce4d59b1550.png)

**Comment by AndrewShmig** [comment]
@mkll добрый день :)
Мы тоже так подумали, поэтому... обновитесь!)

**Comment by AndrewShmig** [comment]
@mkll в самой последней версии правда есть маленький недочет: https://github.com/AndrewShmig/Vkontakte-iOS-SDK-LV/issues/62 (а был решением этой проблемы: https://github.com/AndrewShmig/Vkontakte-iOS-SDK-LV/issues/61)
Я его на днях (скорее всего даже сегодня) исправлю, поэтому не забывайте обновляться.

**Comment by mkll** [comment]
Во как. :+1:
