### ISSUE TITLE
Methods(assistant table)

### ISSUE THREAD

**Issue by agitka** [AndrewShmig/Vkontakte-iOS-SDK-LV#64]
| Name | GET | POST |
| :-- | :-: | :-: |
| Groups Methods | :floppy_disk: | :floppy_disk: |
| – groupsIsMember: | :white_check_mark: |  |
| – groupsGetByID: | :white_check_mark: |  |
| – groupsGet: | :white_check_mark: |  |
| – groupsGetMembers: | :white_check_mark: |  |
| – groupsJoin: | :white_check_mark: |  |
| – groupsLeave: | :white_check_mark: |  |
| – groupsSearch: | :white_check_mark: |  |
| – groupsGetInvites: | :white_check_mark: |  |
| – groupsBanUser: |  | :white_check_mark: |
| – groupsUnbanUser: |  | :white_check_mark: |
| – groupsGetBanned: | :white_check_mark: |  |
| Places Methods | :floppy_disk: | :floppy_disk: |
| – placesAdd: |  | :white_check_mark: |
| – placesGetByID: | :white_check_mark: |  |
| – placesSearch: | :white_check_mark: |  |
| – placesCheckIn: |  | :white_check_mark: |
| – placesGetCheckins: | :white_check_mark: |  |
| – placesGetTypes: | :white_check_mark: |  |
| – placesGetContries: | :white_check_mark: |  |
| – placesGetRegions: | :white_check_mark: |  |
| – placesGetStreetByID: | :white_check_mark: |  |
| – placesGetCountryByID: | :white_check_mark: |  |
| – placesGetCities: | :white_check_mark: |  |
| – placesGetCityByID: | :white_check_mark: |  |
| User Methods | :floppy_disk: | :floppy_disk: |
| – info | :white_check_mark: |  |
| – info: | :white_check_mark: |  |
| – search: | :white_check_mark: |  |
| – subscriptions: | :white_check_mark: |  |
| – followers: | :white_check_mark: |  |
| – isAppUser: | :white_check_mark: |  |
| Stats Methods | :floppy_disk: | :floppy_disk: |
| – statsGet: | :white_check_mark: |  |
| Board Methods | :floppy_disk: | :floppy_disk: |
| – boardGetTopics: | :white_check_mark: |  |
| – boardGetComments: | :white_check_mark: |  |
| – boardAddTopic: |  | :white_check_mark: |
| – boardAddComment: |  | :white_check_mark: |
| – boardDeleteTopic: |  | :white_check_mark: |
| – boardEditTopic: |  | :white_check_mark: |
| – boardEditComment: |  | :white_check_mark: |
| – boardRestoreComment: |  | :white_check_mark: |
| – boardDeleteComment: |  | :white_check_mark: |
| – boardOpenTopic: |  | :white_check_mark: |
| – boardCloseTopic: |  | :white_check_mark: |
| – boardFixTopic: |  | :white_check_mark: |
| – boardUnfixTopic: |  | :white_check_mark: |
| Utils Methods | :floppy_disk: | :floppy_disk: |
| – utilsCheckLink: |  | :white_check_mark: |
| – utilsResolveScreenName: | :white_check_mark: |  |
| – utilsGetServerTime: | :white_check_mark: |  |
| Likes Methods | :floppy_disk: | :floppy_disk: |
| – likesGetList: | :white_check_mark: |  |
| – likesAdd: |  | :white_check_mark: |
| – likesDelete: |  | :white_check_mark: |
| – likesIsLiked: | :white_check_mark: |  |
| Status Methods | :floppy_disk: | :floppy_disk: |
| – statusGet: | :white_check_mark: |  |
| – statusSet: |  | :white_check_mark: |
| Database Methods | :floppy_disk: | :floppy_disk: |
| – databaseGetCountries: | :white_check_mark: |  |
| – databaseGetRegions: | :white_check_mark: |  |
| – databaseGetStreetsById: | :white_check_mark: |  |
| – databaseGetCountriesById: | :white_check_mark: |  |
| – databaseGetCities: | :white_check_mark: |  |
| – databaseGetCitiesById: | :white_check_mark: |  |
| – databaseGetUniversities: | :white_check_mark: |  |
| – databaseGetSchools: | :white_check_mark: |  |
| – databaseGetFaculties: | :white_check_mark: |  |
| Audio Methods | :floppy_disk: | :floppy_disk: |
| – audioGet: | :white_check_mark: |  |
| – audioGetByID: | :white_check_mark: |  |
| – audioGetLyrics: | :white_check_mark: |  |
| – audioSearch: | :white_check_mark: |  |
| – audioGetUploadServer: | :white_check_mark: |  |
| – audioSave: |  | :white_check_mark: |
| – audioAdd: |  | :white_check_mark: |
| – audioDelete: |  | :white_check_mark: |
| – audioEdit: |  | :white_check_mark: |
| – audioReorder: |  | :white_check_mark: |
| – audioRestore: |  | :white_check_mark: |
| – audioGetAlbums: | :white_check_mark: |  |
| – audioAddAlbum: |  | :white_check_mark: |
| – audioEditAlbum: |  | :white_check_mark: |
| – audioDeleteAlbum: |  | :white_check_mark: |
| – audioMoveToAlbum: |  | :white_check_mark: |
| – audioSetBroadcast: |  | :white_check_mark: |
| – audioGetBroadcastList: | :white_check_mark: |  |
| – audioGetRecommendations: | :white_check_mark: |  |
| – audioGetPopular: | :white_check_mark: |  |
| – audioGetCount: | :white_check_mark: |  |
| Docs Methods | :floppy_disk: | :floppy_disk: |
| – docsGet: | :white_check_mark: |  |
| – docsGetByID: | :white_check_mark: |  |
| – docsGetUploadServer: | :white_check_mark: |  |
| – docsGetWallUploadServer: | :white_check_mark: |  |
| – docsSave: |  | :white_check_mark: |
| – docsDelete: |  | :white_check_mark: |
| – docsAdd: |  | :white_check_mark: |
| Notifications Methods | :floppy_disk: | :floppy_disk: |
| – notificationsGet: | :white_check_mark: |  |
| – notificationsMarkeAsViewed: |  | :white_check_mark: |
| Friends Methods | :floppy_disk: | :floppy_disk: |
| – friendsGet: | :white_check_mark: |  |
| – friendsGetOnline: | :white_check_mark: |  |
| – friendsGetMutual: | :white_check_mark: |  |
| – friendsGetRecent: | :white_check_mark: |  |
| – friendsGetRequests: | :white_check_mark: |  |
| – friendsAdd: |  | :white_check_mark: |
| – friendsEdit: |  | :white_check_mark: |
| – friendsDelete: |  | :white_check_mark: |
| – friendsGetLists: | :white_check_mark: |  |
| – friendsAddList: |  | :white_check_mark: |
| – friendsEditList: |  | :white_check_mark: |
| – friendsDeleteList: |  | :white_check_mark: |
| – friendsGetAppUsers: | :white_check_mark: |  |
| – friendsGetByPhones: | :white_check_mark: |  |
| – friendsDeleteAllRequests: |  | :white_check_mark: |
| – friendsGetSuggestions: | :white_check_mark: |  |
| – friendsAreFriends: | :white_check_mark: |  |
| Account Methods | :floppy_disk: | :floppy_disk: |
| – accountGetCounters: | :white_check_mark: |  |
| – accountSetNameInMenu: |  | :white_check_mark: |
| – accountSetOnline: |  | :white_check_mark: |
| – accountImportContacts: |  | :white_check_mark: |
| – accountRegisterDevice: |  | :white_check_mark: |
| – accountUnregisterDevice: |  | :white_check_mark: |
| – accountSetSilenceMode: |  | :white_check_mark: |
| – accountGetPushSettings: | :white_check_mark: |  |
| – accountGetAppPermissions: | :white_check_mark: |  |
| – accountGetActiveOffers: | :white_check_mark: |  |
| – accountBanUser: |  | :white_check_mark: |
| – accountUnbanUser: |  | :white_check_mark: |
| – accountGetBanned: | :white_check_mark: |  |
| Photos Methods | :floppy_disk: | :floppy_disk: |
| – photosCreateAlbum: |  | :white_check_mark: |
| – photosEditAlbum: |  | :white_check_mark: |
| – photosGetAlbums: | :white_check_mark: |  |
| – photosGet: | :white_check_mark: |  |
| – photosGetAlbumsCount: | :white_check_mark: |  |
| – photosGetProfile: | :white_check_mark: |  |
| – photosGetByID: | :white_check_mark: |  |
| – photosGetUploadServer: | :white_check_mark: |  |
| – photosGetProfileUploadServer: | :white_check_mark: |  |
| – photosGetChatUploadServer: | :white_check_mark: |  |
| – photosSaveProfilePhoto: |  | :white_check_mark: |
| – photosSaveWallPhoto: |  | :white_check_mark: |
| – photosGetWallUploadServer: | :white_check_mark: |  |
| – photosGetMessagesUploadServer: | :white_check_mark: |  |
| – photosSaveMessagesPhoto: |  | :white_check_mark: |
| – photosSearch: | :white_check_mark: |  |
| – photosSave: |  | :white_check_mark: |
| – photosEdit: |  | :white_check_mark: |
| – photosMove: |  | :white_check_mark: |
| – photosMakeCover: |  | :white_check_mark: |
| – photosReorderAlbums: |  | :white_check_mark: |
| – photosReorderPhotos: |  | :white_check_mark: |
| – photosGetAll: | :white_check_mark: |  |
| – photosGetUserPhotos: | :white_check_mark: |  |
| – photosDeleteAlbum: |  | :white_check_mark: |
| – photosDelete: |  | :white_check_mark: |
| – photosConfirmTagWithCustomOptions: |  | :white_check_mark: |
| – photosGetComments: | :white_check_mark: |  |
| – photosGetAllComments: | :white_check_mark: |  |
| – photosCreateComment: |  | :white_check_mark: |
| – photosDeleteComment: |  | :white_check_mark: |
| – photosRestoreComment: |  | :white_check_mark: |
| – photosEditComment: |  | :white_check_mark: |
| – photosGetTags: | :white_check_mark: |  |
| – photosPutTag: |  | :white_check_mark: |
| – photosRemoveTag: |  | :white_check_mark: |
| – photosGetNewTags: | :white_check_mark: |  |
| Pages Methods | :floppy_disk: | :floppy_disk: |
| – pagesGet: | :white_check_mark: |  |
| – pagesSave: |  | :white_check_mark: |
| – pagesSaveAccess: |  | :white_check_mark: |
| – pagesGetHistory: | :white_check_mark: |  |
| – pagesGetTitles: | :white_check_mark: |  |
| – pagesGetVersion: | :white_check_mark: |  |
| – pagesParseWiki: |  | :white_check_mark: |
| Notes Methods | :floppy_disk: | :floppy_disk: |
| – notesGet: | :white_check_mark: |  |
| – notesGetByID: | :white_check_mark: |  |
| – notesGetFriendsNotes: | :white_check_mark: |  |
| – notesAdd: |  | :white_check_mark: |
| – notesEdit: |  | :white_check_mark: |
| – notesDelete: |  | :white_check_mark: |
| – notesGetComments: | :white_check_mark: |  |
| – notesCreateComment: |  | :white_check_mark: |
| – notesEditComment: |  | :white_check_mark: |
| – notesDeleteComment: |  | :white_check_mark: |
| – notesRestoreComment: |  | :white_check_mark: |
| Newsfeed Methods | :floppy_disk: | :floppy_disk: |
| – newsfeedGet: | :white_check_mark: |  |
| – newsfeedGetRecommended: | :white_check_mark: |  |
| – newsfeedGetComments: | :white_check_mark: |  |
| – newsfeedGetMentions: | :white_check_mark: |  |
| – newsfeedGetBanned: | :white_check_mark: |  |
| – newsfeedAddBan: |  | :white_check_mark: |
| – newsfeedDeleteBan: |  | :white_check_mark: |
| – newsfeedSearch: | :white_check_mark: |  |
| – newsfeedGetLists: | :white_check_mark: |  |
| – newsfeedUnsubscribe: |  | :white_check_mark: |
| Polls Methods | :floppy_disk: | :floppy_disk: |
| – pollsGetByID: | :white_check_mark: |  |
| – pollsAddVote: |  | :white_check_mark: |
| – pollsDeleteVote: |  | :white_check_mark: |
| – pollsGetVoters: | :white_check_mark: |  |
| Messages Methods | :floppy_disk: | :floppy_disk: |
| – messagesGet: | :white_check_mark: |  |
| – messagesGetDialogs: | :white_check_mark: |  |
| – messagesGetByID: | :white_check_mark: |  |
| – messagesSearch: | :white_check_mark: |  |
| – messagesGetHistory: | :white_check_mark: |  |
| – messagesSend: |  | :white_check_mark: |
| – messagesDelete: |  | :white_check_mark: |
| – messagesDeleteDialog: |  | :white_check_mark: |
| – messagesRestore: |  | :white_check_mark: |
| – messagesMarkAsNew: |  | :white_check_mark: |
| – messagesMarkAsRead: |  | :white_check_mark: |
| – messagesMarkAsImportant: |  | :white_check_mark: |
| – messagesGetLongPollServer: | :white_check_mark: |  |
| – messagesGetLongPollHistory: | :white_check_mark: |  |
| – messagesGetChat: | :white_check_mark: |  |
| – messagesCreateChat: |  | :white_check_mark: |
| – messagesEditChat: |  | :white_check_mark: |
| – messagesGetChatUsers: | :white_check_mark: |  |
| – messagesSetActivity: |  | :white_check_mark: |
| – messagesSearchDialogs: | :white_check_mark: |  |
| – messagesAddChatUser: |  | :white_check_mark: |
| – messagesRemoveChatUser: |  | :white_check_mark: |
| – messagesGetLastActivity: | :white_check_mark: |  |
| – messagesSetChatPhoto: |  | :white_check_mark: |
| – messagesDeleteChatPhoto: |  | :white_check_mark: |
| Ads Methods | :floppy_disk: | :floppy_disk: |
| – adsGetAccounts: | :white_check_mark: |  |
| – adsGetClients: | :white_check_mark: |  |
| – adsCreateClients: |  | :white_check_mark: |
| – adsUpdateClients: |  | :white_check_mark: |
| – adsDeleteClients: |  | :white_check_mark: |
| – adsGetCampaigns: | :white_check_mark: |  |
| – adsCreateCampaigns: |  | :white_check_mark: |
| – adsUpdateCampaings: |  | :white_check_mark: |
| – adsDeleteCampaings: |  | :white_check_mark: |
| – adsGet: | :white_check_mark: |  |
| – adsGetLayout: | :white_check_mark: |  |
| – adsGetTargeting: | :white_check_mark: |  |
| – adsCreate: |  | :white_check_mark: |
| – adsUpdate: |  | :white_check_mark: |
| – adsDelete: |  | :white_check_mark: |
| – adsGetStatistics: | :white_check_mark: |  |
| – adsGetDemographics: | :white_check_mark: |  |
| – adsGetBudget: | :white_check_mark: |  |
| – adsGetOfficeUsers: | :white_check_mark: |  |
| – adsAddOfficeUsers: |  | :white_check_mark: |
| – adsRemoveOfficeUsers: |  | :white_check_mark: |
| – adsGetTargetingStats: | :white_check_mark: |  |
| – adsGetSuggestions: | :white_check_mark: |  |
| – adsGetCategories: | :white_check_mark: |  |
| – adsGetUploadURL: | :white_check_mark: |  |
| – adsGetVideoUploadURL: | :white_check_mark: |  |
| – adsGetFloodStats: | :white_check_mark: |  |
| – adsGetRejectionReason: | :white_check_mark: |  |
| – adsCreateTargetGroup: |  | :white_check_mark: |
| – adsUpdateTargetGroup: |  | :white_check_mark: |
| – adsDeleteTargetGroup: |  | :white_check_mark: |
| – adsGetTargetGroups: | :white_check_mark: |  |
| – adsImportTargetContacts: |  | :white_check_mark: |
| Apps Methods | :floppy_disk: | :floppy_disk: |
| – appsGetCatalog: | :white_check_mark: |  |
| Search Methods | :floppy_disk: | :floppy_disk: |
| – searchGetHints: | :white_check_mark: |  |
| Wall Methods | :floppy_disk: | :floppy_disk: |
| – wallGet: | :white_check_mark: |  |
| – wallGetByID: | :white_check_mark: |  |
| – wallSavePost: |  | :white_check_mark: |
| – wallPost: |  | :white_check_mark: |
| – wallRepost: |  | :white_check_mark: |
| – wallGetReposts: | :white_check_mark: |  |
| – wallEdit: |  | :white_check_mark: |
| – wallDelete: |  | :white_check_mark: |
| – wallRestore: |  | :white_check_mark: |
| – wallGetComments: | :white_check_mark: |  |
| – wallAddComment: |  | :white_check_mark: |
| – wallDeleteComment: |  | :white_check_mark: |
| – wallRestoreComment: |  | :white_check_mark: |
| Fave Methods | :floppy_disk: | :floppy_disk: |
| – faveGetUsers: | :white_check_mark: |  |
| – faveGetPhotos: | :white_check_mark: |  |
| – faveGetPosts: | :white_check_mark: |  |
| – faveGetVideos: | :white_check_mark: |  |
| – faveGetLinks: | :white_check_mark: |  |
| Video Methods | :floppy_disk: | :floppy_disk: |
| – videoGet: | :white_check_mark: |  |
| – videoEdit: |  | :white_check_mark: |
| – videoAdd: |  | :white_check_mark: |
| – videoSave: |  | :white_check_mark: |
| – videoDelete: |  | :white_check_mark: |
| – videoRestore: |  | :white_check_mark: |
| – videoSearch: | :white_check_mark: |  |
| – videoGetUserVideos: | :white_check_mark: |  |
| – videoGetAlbums: | :white_check_mark: |  |
| – videoAddAlbum: |  | :white_check_mark: |
| – videoEditAlbum: |  | :white_check_mark: |
| – videoDeleteAlbum: |  | :white_check_mark: |
| – videoMoveToAlbum: |  | :white_check_mark: |
| – videoGetComments: | :white_check_mark: |  |
| – videoCreateComment: |  | :white_check_mark: |
| – videoDeleteComment: |  | :white_check_mark: |
| – videoRestoreComment: |  | :white_check_mark: |
| – videoEditComment: |  | :white_check_mark: |
| – videoGetTags: | :white_check_mark: |  |
| – videoPutTag: |  | :white_check_mark: |
| – videoRemoveTag: |  | :white_check_mark: |
| – videoGetNewTags: | :white_check_mark: |  |
| – videoReport: |  | :white_check_mark: |
| Execute Methods | :floppy_disk: | :floppy_disk: |
| – execute: |  | :white_check_mark: |
| – executePredefinedProcedureWithName:options: |  | :white_check_mark: |

**Comment by AndrewShmig** [comment]
Wow! Really nice!
Just need to fill it with right values. Five minutes and I'll commit updated version of SDK with fixed GET/POST requests.

**Comment by agitka** [comment]
Now my values may conflict with yours. I might sync after commit.

**Comment by agitka** [comment]
In addition, I see few typos.

**Comment by agitka** [comment]
photosConfirmTagWithCusomOptions:

**Comment by agitka** [comment]
Ho ho ho.

**Comment by AndrewShmig** [comment]
@agitka wow! thats really cool!
Fixed some small mistakes with GET/POST. 

How do you think where I should publish this? Or leave it here with "Documentation" tag?

**Comment by agitka** [comment]
@AndrewShmig I don't know that appledoc support markdown syntax, but it's nice helper for new users. I prefer gh-pages is a prominent place for this.

**Comment by AndrewShmig** [comment]
@agitka appledoc supports GitHub markdown? wow! Did't know either.

**Comment by agitka** [comment]
@AndrewShmig you misunderstood. I don't know about full compatibility. Especially about tables.

**Comment by agitka** [comment]
Fix.
