### ISSUE TITLE
Возможность удалить access token 

### ISSUE THREAD

**Issue by bekzattt** [AndrewShmig/Vkontakte-iOS-SDK-LV#67]
Добавить возможность удалить  access token  для logout'а  пользователя в VKUser , наподобие
[FBSession.activeSession closeAndClearTokenInformation]  в api фэйсбука

**Comment by bekzattt** [comment]
для выхода помогло 
-(void)logoutButtonPressed:(id)sender {  
    [[VKConnector sharedInstance] clearCookies];
    [[VKStorage sharedStorage] clean];

```
NSLog(@"VKUSER accessToken %@",[VKUser currentUser].accessToken);

[FBSession.activeSession closeAndClearTokenInformation];

AppDelegate* appDelegate =(AppDelegate *) [UIApplication sharedApplication].delegate;
[appDelegate resetApp];
```

}

**Comment by AndrewShmig** [comment]
@bekzattt 
Добрый день!

У меня два замечания-вопроса:
1) Зачем вам именно удалять токен доступа?
2) Использование метода 

``` objective-c
[[VKStorage sharedStorage] clean];
```

при наличии нескольких пользователей в хранилище не совсем верное решение.
Обратите внимание на связку методов:

``` objective-c
/** Удаляет из хранилища указанный элемент

@param item элемент хранилища
*/
- (void)removeItem:(VKStorageItem *)item;
```

и 

``` objective-c
/** Получение элемента хранилища по пользовательскому идентификатору

@param userID пользовательский идентификатор
@return экземпляр класса VKStorageItem, либо nil, если элемента в хранилище
*/
- (VKStorageItem *)storageItemForUserID:(NSUInteger)userID;
```
