### ISSUE TITLE
No Longer loads Oauth

### ISSUE THREAD

**Issue by imclean** [AndrewShmig/Vkontakte-iOS-SDK-LV#69]
CONNECTION error: Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo=0xb6a9e30 {NSErrorFailingURLStringKey=https://oauth.vk.com/authorize?display=mobile&response_type=token&redirect_uri=https://oauth.vk.com/blank.html&scope=photos,friends,wall,audio,video&client_id=xxxxxx, NSErrorFailingURLKey=https://oauth.vk.com/authorize?display=mobile&response_type=token&redirect_uri=https://oauth.vk.com/blank.html&scope=photos,friends,wall,audio,video&client_id=xxxxxx, NSLocalizedDescription=Could not connect to the server., NSUnderlyingError=0xb745d60 "Could not connect to the server."}

where xxxxxx is our key that worked perfectly yesterday, however loading this in a browser works ok, just not on the iOS sim or device.

**Comment by AndrewShmig** [comment]
Hmm... very strange, no updates were made since than.

**Comment by imclean** [comment]
Yeah, was working fine, but now no longer loads. Just get the "Could not connect to the server." error 1004

**Comment by AndrewShmig** [comment]
@imclean maybe something is blocking your connections?
I have checked it again and again and it works fine... I'll think about possible problems which may cause such behavior.

Can you provide more information? Or thats all what you get?

**Comment by imclean** [comment]
@AndrewShmig It works in the browser, but not in the sim, which is strange, It returns with the error within a few seconds of showing the webview, then the webview just closes (because there is an error), I'm not blocked as I am working at home and has been connecting just fine before, I'll try another network and see how it goes, I'll let you know, Thanks!

Great work by the way!

**Comment by imclean** [comment]
@AndrewShmig seems to be working now :-)

Maybe the NSA are watching me!!

Thanks for your input!

**Comment by AndrewShmig** [comment]
@imclean heh... great news!
But now I am adding extended loggers, so someone else could just copy-paste me that logs and I can find causes of a problem much faster.

Cheers!
