### ISSUE TITLE
User email

### ISSUE THREAD

**Issue by imclean** [AndrewShmig/Vkontakte-iOS-SDK-LV#72]
I noticed that [user info] doesn't give the users email, is there no way to get an email from the api of the logged in user?

Thanks!

Iain

**Comment by AndrewShmig** [comment]
There is no way to get user's email.
You can read about it here: https://vk.com/dev/users.get

All you can get is: nickname, screen_name, sex, bdate, city, country, timezone, photo_50, photo_100, photo_200_orig, has_mobile, contacts, education, online, counters, relation, last_seen, status, can_write_private_message, can_see_all_posts, can_see_audio, can_post, universities, schools,verified
