### ISSUE TITLE
Не обновляется токен

### ISSUE THREAD

**Issue by HoldFast88** [AndrewShmig/Vkontakte-iOS-SDK-LV#77]
Столкнулся в своем приложении с проблемой, что не пересохраняется токен в хранилище при истечении его срока давности. Проблему вижу в том, что в методе saveStorage класса VKStorage для объекта класса NSUserDefaults не вызывается synchronize. Получается, что синхронизация откладывается на следующий цикл приложения. А, учитывая, что метод делегата вызывается сразу же после сохранения токена в хранилище, то не факт, что дефолтсы к тому времени синхронизируются.

**Comment by HoldFast88** [comment]
Вдогонку - если при запроса выяснится, что у токена истек срок жизни, то при получении нового у  объекта VKUser не обновится сторадж поле, т.к. оно задается в конструкторе. Следовательно при проверке isExpired всегда будет приходить тот, который задан юзеру при инициализации синглтона.

**Comment by AndrewShmig** [comment]
@HoldFast88 спасибо за репорт, надо глянуть будет (постараюсь в течение дней двух-трех посмотреть что там).
Если готовы пулл реквест сделать - буду рад.
