### ISSUE TITLE
Podfile рядом с исходниками

### ISSUE THREAD

**Issue by delebedev** [AndrewShmig/Vkontakte-iOS-SDK-LV#79]
Как я понимаю сейчас подфайл лежит в центральном spec-repo, мне кажется гораздо логичнее его хранить тут - мэинтэйнить легче

**Comment by AndrewShmig** [comment]
@garnett а каким образом будет происходить "сливание" пода в основной спек-реп?

**Comment by delebedev** [comment]
@AndrewShmig я не могу почему-то найти это в гайдах к CocoaPods (вроде смотреть нужно сюда http://guides.cocoapods.org/making/specs-and-specs-repo.html#how-does-the-specs-repo-work?)
но воркфлоу обычно такой - в мастер репо идут спеки, разработчики которых поды не саппортят, а если создатель сам хочет поддерживать cocoapod - спека кладется рядом с проектом (например, AFNetworking https://github.com/AFNetworking/AFNetworking).

**Comment by AndrewShmig** [comment]
@garnett хорошо, по возможности гляну, что там и как... может действительно стоит перенести сюда.
Если что, то можете пулреквест сделать - приму.

**Comment by ghost** [comment]
Можно сделать пару хуков:
1) перед простановкой тега версии апдейтится локальный podspec-файл и делается коммит
2) после тегирования версии делается пуш мастера на гитхаб, создание в локальной копии CocoaPods/Specs папки для новой версии podspec, его копирование в эту папку из папки проекта, коммит и pull-request CocoaPods/Specs.
Как я понимаю, всё же нет автоматического апдейта.

**Comment by AndrewShmig** [comment]
@virasio в таком случае мне проще просто изменять уже имеющийся подспек в CocoaPods и не париться :)

**Comment by ghost** [comment]
@AndrewShmig я тут немного накосячил, попытавшись сам его изменить, т.к. хотелось новую версию, и не заметил, что это только комментарий 4.4.1 у вас, а тега нет. :) (https://github.com/CocoaPods/Specs/pull/6344)

**Comment by AndrewShmig** [comment]
@virasio добавил тег.
