### ISSUE TITLE
Версия API Вконтакте

### ISSUE THREAD

**Issue by ghost** [AndrewShmig/Vkontakte-iOS-SDK-LV#80]
Для многих методов отличается результат в зависимости от версии API, было бы не плохо иметь возможность указывать эту версию.

**Comment by AndrewShmig** [comment]
@alaija спасибо, действительно хорошее замечание.
попробуем в ближайшее время реализовать.

**Comment by AndrewShmig** [comment]
@alaija вы знаете, я немного стормозил.
Вы можете передавать параметр версии АПИ методу, как собственной любой другой параметр метода.

**Comment by ghost** [comment]
Мне кажется было бы логично сделать это глобально при создании RequestManager'a ибо сегодня апи работает так, завтра поменяют и без этого параметра начнет работать по другому.

**Comment by AndrewShmig** [comment]
@alaija в таком случае СДК будет слишком зависима от наименования параметров и прочих условий каких-то. 
Ведь, если я "впишу" в RequestManager еще и выбор версии, то достаточно им изменить наименование параметра, как приложение либо будет падать, либо некорректно работать... в итоге я получу сообщения, что что-то отвалилось и тд и тп, а это излишняя работа по перепроверке.

Всегда есть возможность просто форкнуть и добавить нужный функционал :)

Я запомню вашу просьбу, если еще кто обратится с подобной, тогда подумаем.

**Comment by ghost** [comment]
На счет форкнуть без проблем, я то уже все что мне надо сделал, просто думал помочь интересному проекту, пока контакт свое сломаное в очередной раз апи чинит...

**Comment by AndrewShmig** [comment]
@alaija пул реквест и я приму)
пока же мне всё таки не особо нравится это самое ограничение по версиям на каждый VKRequestManager. В случае чего мне необходимо будет создавать новый мэнеджер, где было бы проще указать параметр "v" и всё.

**Comment by ghost** [comment]
Не, мой фикс на пулреквест не катит, там тупо костыль. Если проблем о которых вы говорите, не выявлю, то может допилю и отправлю Вам.
