### ISSUE TITLE
kVkontakteBlankURL

### ISSUE THREAD

**Issue by Friend-LGA** [AndrewShmig/Vkontakte-iOS-SDK-LV#81]
static NSString *const kVkontakteBlankURL = @"https://oauth.vk.com/blank.html";

Привет, сегодня случайно проверил авторизацию, и теперь видимо при нажатии кнопки "отмена" выдается не бланк урл как раньше, а немного другой:

static NSString *const kVkontakteBlankURL_ver2 = @"http://vk.com/login.php?act=slogin&role=fast&no_redirect=1&to=&s=0";

Так что вот, думаю было бы не плохо добавить, а то 
[self.delegate VKConnector:self willHideWebView:webView];
не вызывается.

**Comment by AndrewShmig** [comment]
@Friend-LGA привет. Да, я уже получал подобные сообщения, но у меня остается вопрос: а это окончательный вариант, который ВК реализует? Документация просто не изменилась и, если я внесу коррективы в СДК, а в ВК это пофиксят, то приложение будет некорректно работать.
Поэтому я бы предложил вам пока использовать этот костыль только у себя, а вот, если ВК документацию обновят и укажут этот момент, то я исправлю здесь.

**Comment by Friend-LGA** [comment]
ок :) спасибо за разъяснения
