### ISSUE TITLE
Ожидется ли поддержка VK SDK http://vk.com/dev/ios_sdk ? Если да, то когда?

### ISSUE THREAD

**Issue by yulia-mykhailova** [AndrewShmig/Vkontakte-iOS-SDK-LV#82]

**Comment by AndrewShmig** [comment]
О какой поддержке идёт речь? Что в текущей версии СДК вы хотите увидеть перенятого от контактовской СДК?

**Comment by yulia-mykhailova** [comment]
Лично меня интересует возможность логина через нативный апп. Это вообще возможно? Или нужно будет на прямую юзать полностью их СДК для этого?

**Comment by AndrewShmig** [comment]
@miumi-u бегло глянул, но не вчитывался.
Я про этот СДК от ВК узнал только после того, как свою версию закончил. Поэтому я думаю лучше спросить тех, кто его использовал (если такие есть).

**Comment by yulia-mykhailova** [comment]
@AndrewShmig Ох, если они официально анонсировали бету 5 дней назад, может еще никто и не решился использовать, после праздников особенно). Ну, буду тогда разбираться что там и как.

**Comment by AndrewShmig** [comment]
@miumi-u ну вот тем более :) пусть погоняют, пусть оттестируют, а там будет видно, что и как можно "перенять".
