### ISSUE TITLE
Проблема с отменой логина

### ISSUE THREAD

**Issue by yulia-mykhailova** [AndrewShmig/Vkontakte-iOS-SDK-LV#83]
Ситуация такая что если ошибиться при логине, и потом нажать Cancel вконтакте возвращает https://oauth.vk.com/error?err=8 и эта ситуация никак не обрабатывается внутри СДК. Это проблема собственно ВК и такого рода ошибки должны обрабатываться пользователем СДК или возможен апдейт с обработкой такого рода ситуаций?

**Comment by AndrewShmig** [comment]
Да, об этом я уведомлён уже давно, но конкретных изменений вносить в СДК пока не намерен. Почему? Вот здесь подобный случай: https://github.com/AndrewShmig/Vkontakte-iOS-SDK-LV/issues/81
Пока в документации не будет четко определено что и как - будем следовать тому, что там сейчас написано.

Советую подобные мелкие проблемы решать своими "силами" пока. Не хочется городить костыли в основной ветке и на каждый чих разработчиков ВК перепиливать и говнокодить.

**Comment by yulia-mykhailova** [comment]
Да, меня тоже удивило что описания такого поведения и ошибки нигде нет на официальных ресурсах. Ну что ж, будем подпирать собственными силами пока они не намерятся написать хорошую документацию. Спасибо за ответ!
