### ISSUE TITLE
Project as static library or CocoaPod

### ISSUE THREAD

**Issue by virl** [AndrewShmig/Vkontakte-iOS-SDK-LV#84]
Please distribute project as static library or as CocoaPod.

**Comment by AndrewShmig** [comment]
Hi!

Whats wrong with these?
1. http://cocoadocs.org/docsets/Vkontakte-iOS-SDK-LV/4.3.2/
2. https://github.com/CocoaPods/Specs/tree/master/Vkontakte-iOS-SDK-LV
3. https://www.cocoacontrols.com/controls/vkontakte-ios-sdk

I'll think about distributing as static library.

Thanks.

**Comment by virl** [comment]
Thanks.
