### ISSUE TITLE
Авторизация с иностранного IP и подтверждение вводом телефонного номера

### ISSUE THREAD

**Issue by AndrewShmig** [AndrewShmig/Vkontakte-iOS-SDK-LV#87]
![screen shot 2014-02-27 at 9 07 29 pm](https://f.cloud.github.com/assets/2047836/2285164/af7a7e60-9fd1-11e3-8322-be6b121b003a.png)

**Comment by AndrewShmig** [comment]
![screen shot 2014-02-27 at 9 35 32 pm](https://f.cloud.github.com/assets/2047836/2285491/968cb87e-9fd5-11e3-9523-4185caf3067d.png)

**Comment by AndrewShmig** [comment]
В документации: https://vk.com/dev/need_validation

**Comment by sanchosrancho** [comment]
Кстати, ошибка [need validation](https://vk.com/dev/need_validation) описана только в русской ветке документации ВК. Будьте внимательны.

**Comment by AndrewShmig** [comment]
@sanchosrancho русской ветке? Хм, я стараюсь в исходниках и в AppleDoc описывать на англ. Если речь о документации 2 версии, то она уже давно позади и дополняться и обновляться не будет.

**Comment by sanchosrancho** [comment]
@AndrewShmig речь идет о русской документации ВКонтакте. Т.е. если на vk.com переключить язык  интерфейса на английский и перейти по ссылке, то информации об ошибке вы не увидите, так данная страница на английском языке не существует.

**Comment by AndrewShmig** [comment]
@sanchosrancho вот вы о чем, понял.
