### ISSUE TITLE
VKConnectorDelegate

### ISSUE THREAD

**Issue by yadgarov** [AndrewShmig/Vkontakte-iOS-SDK-LV#88]
Здравствуйте!

Не могли бы вы добавить в протокол VKConnectorDelegate еще один метод, оповещающий о том, что загрузка в webView завершена? Дело в том, что я использую свой activityIndicator и мне нужно знать, в какой момент его остановить.

**Comment by AndrewShmig** [comment]
Готово. 
Добавил два метода, которые сообщают о начале загрузке и завершении загрузки содержимого UIWebView, обновлена документация.

**Comment by yadgarov** [comment]
Спасибо большое!

10 марта 2014 г., 19:25 пользователь Andrew Shmig
notifications@github.comнаписал:

> Готово.
> Добавил два метода, которые сообщают о начале загрузке и завершении
> загрузки содержимого UIWebView, обновлена документация.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/AndrewShmig/Vkontakte-iOS-SDK-LV/issues/88#issuecomment-37194331
> .

## 

_С уважением, Искандер Ядгаров_

**Comment by yadgarov** [comment]
А я смогу подгрузить обновленную версию через поды?

**Comment by AndrewShmig** [comment]
Эммм, нет :)
Чуть позже обновлю. Надеюсь не забуду.

---

С уважением,
Шмиг Андрей Андреевич

Skype: sky-dos
Email: andrewshmig@yandex.ru

**Comment by yadgarov** [comment]
Хорошо. Если что, я напомню)

**Comment by AndrewShmig** [comment]
@red-naks Скоро можно будет обновиться.
https://github.com/CocoaPods/Specs/pull/9035 Обновил под.

**Comment by yadgarov** [comment]
Благодарю)

**Comment by yadgarov** [comment]
Есть еще одно небольшое неудобство, которое побудило меня использовать свой activityIndicator. Дело в том, что если задавать размеры webView используя constraints, то нет возможности правильно расположить стандартный activityIndicator, так как его позиция задается только единожды, в начале создания (а в это время размеры моего webView еще нулевые. 

Я предлагаю располагать activityIndicator через ограничения.

**Comment by AndrewShmig** [comment]
Что-то мне подсказывает, что было неплохо вообще убрать activityIndicator из исходников. Это решит проблему кастомных индикаторов и немного упростит/облегчит код коннектора.
Пожалуй, сделаю.

---

С уважением,
Шмиг Андрей Андреевич

Skype: sky-dos
Email: andrewshmig@yandex.ru

**Comment by yadgarov** [comment]
Неплохое решение)

11 марта 2014 г., 17:28 пользователь Andrew Shmig
notifications@github.comнаписал:

> Что-то мне подсказывает, что было неплохо вообще убрать activityIndicator
> из исходников. Это решит проблему кастомных индикаторов и немного
> упростит/облегчит код коннектора.
> Пожалуй, сделаю.
> 
> ---
> 
> С уважением,
> Шмиг Андрей Андреевич
> 
> Skype: sky-dos
> Email: andrewshmig@yandex.ru
> 
> On Mar 11, 2014, at 2:18 PM, red-naks notifications@github.com wrote:
> 
> > Есть еще одно небольшое неудобство, которое побудило меня использовать
> > свой activityIndicator. Дело в том, что если задавать размеры webView
> > используя constraints, то нет возможности правильно расположить стандартный
> > activityIndicator, так как его позиция задается только единожды, в начале
> > создания (а в это время размеры моего webView еще нулевые.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/AndrewShmig/Vkontakte-iOS-SDK-LV/issues/88#issuecomment-37294674
> .

## 

_С уважением, Искандер Ядгаров_
